// for testing
image: atlassian/default-image:3

pipelines:
  custom:
    aadroid:
      - parallel:
        - step:
            name: 'Build and Test'
            script:
              - echo "$(date +%Y.%m.%d)" > version.txt
            artifacts:
              - version.txt
