name: Weather

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      versionName:
        description: 'User-facing release version name'
        required: true
        default: "1.0.0"
      versionCode:
        description: 'versionCode or build number'
        required: true
        default: 1

jobs:
  tramline-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.versionCode }} > version.txt
      - uses: actions/upload-artifact@v3
        with:
         name: version
         path: version.txt
