name: Android debug build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      versionName:
        description: 'User-facing release version name'
        required: true
        default: "1.0.0"
      versionCode:
        description: 'versionCode or build number'
        required: true
        default: "1"

jobs:
  debug-build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup versionName regardless of how this action is triggered
        id: version_name
        run: |
          WORKFLOW_INPUT=${{ github.event.inputs.versionName }}
          VERSION_NAME=${WORKFLOW_INPUT:-"1.0.0"}
          echo "ORG_GRADLE_PROJECT_VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Setup versionCode regardless of how this action is triggered
        id: version_code
        run: |
          WORKFLOW_INPUT=${{ github.event.inputs.versionCode }}
          VERSION_CODE=${WORKFLOW_INPUT:-"1"}
          echo "ORG_GRADLE_PROJECT_VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
      
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew
      
      - name: Build debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload build file
        uses: actions/upload-artifact@v3
        with:
          name: debug-build-apk
          path: app/build/outputs/apk/debug/app-debug.apk
